package main

import (
	"fmt"
	"piscine"
)

func main() {
	// fmt.Println(piscine.CheckNumber("Hello"))
	// fmt.Println(piscine.CheckNumber("Hello1")) //checkNumber
	// fmt.Println(piscine.CountAlpha("Hello world"))
	// fmt.Println(piscine.CountAlpha("H e l l o"))
	// fmt.Println(piscine.CountAlpha("H1e2l3l4o"))
	// fmt.Println(piscine.CountChar("Hello World", 'l'))
	// fmt.Println(piscine.CountChar("5  balloons", 5))
	// fmt.Println(piscine.CountChar("   ", ' '))
	// fmt.Println(piscine.CountChar("The 7 deadly sins", '7'))
	// fmt.Print(piscine.PrintIf("abcdefz"))
	// fmt.Print(piscine.PrintIf("abc"))
	// fmt.Print(piscine.PrintIf(""))
	// fmt.Print(piscine.PrintIf("14"))
	// fmt.Print(piscine.PrintIfNot("abcdefz"))
	// fmt.Print(piscine.PrintIfNot("abc"))
	// fmt.Print(piscine.PrintIfNot(""))
	// fmt.Print(piscine.PrintIfNot("14"))
	// fmt.Println(piscine.RectPerimeter(10, 2))
	// fmt.Println(piscine.RectPerimeter(434343, 898989))
	// fmt.Println(piscine.RectPerimeter(10, -2))
	// fmt.Println(piscine.RetainFirstHalf("This is the 1st halfThis is the 2nd half"))
	// fmt.Println(piscine.RetainFirstHalf("A"))
	// fmt.Println(piscine.RetainFirstHalf(""))
	// fmt.Println(piscine.RetainFirstHalf("Hello World"))
	// fmt.Println(piscine.CamelToSnakeCase("HelloWorld"))
	// fmt.Println(piscine.CamelToSnakeCase("helloWorld"))
	// fmt.Println(piscine.CamelToSnakeCase("camelCase"))
	// fmt.Println(piscine.CamelToSnakeCase("CAMELtoSnackCASE"))
	// fmt.Println(piscine.CamelToSnakeCase("camelToSnakeCase"))
	// fmt.Println(piscine.CamelToSnakeCase("hey2"))
	// fmt.Println(piscine.DigitLen(100, 10))
	// fmt.Println(piscine.DigitLen(100, 2))
	// fmt.Println(piscine.DigitLen(-100, 16))
	// fmt.Println(piscine.DigitLen(100, -1))
	// fmt.Print(piscine.FirstWord("hello there"))
    // fmt.Print(piscine.FirstWord(""))
    // fmt.Print(piscine.FirstWord("hello   .........  bye"))
	// fmt.Println(piscine.FishAndChips(4))
	// fmt.Println(piscine.FishAndChips(9))
	// fmt.Println(piscine.FishAndChips(6))
	// fmt.Println(piscine.Gcd(42, 10))
	// fmt.Println(piscine.Gcd(42, 12))
	// fmt.Println(piscine.Gcd(14, 77))
	// fmt.Println(piscine.Gcd(17, 3))
	// fmt.Println(piscine.HashCode("A"))
	// fmt.Println(piscine.HashCode("AB"))
	// fmt.Println(piscine.HashCode("BAC"))
	// fmt.Println(piscine.HashCode("Hello World"))
	// fmt.Print(piscine.LastWord("this        ...       is sparta, then again, maybe    not"))
	// fmt.Print(piscine.LastWord(" lorem,ipsum "))
	// fmt.Print(piscine.LastWord(" "))
	fmt.Println(piscine.RepeatAlpha("abc"))
	fmt.Println(piscine.RepeatAlpha("Choumi."))
	fmt.Println(piscine.RepeatAlpha(""))
	fmt.Println(piscine.RepeatAlpha("abacadaba 01!"))
}
